### ISSUE TITLE
remove bluebird dependency if native promises are available

### ISSUE THREAD

**Issue by neuhaus** [bhoriuchi/readline-promise#1]
I don't need bluebird, I have native promises...

**Comment by bhoriuchi** [comment]
I'll work on this soon. You are correct, there is no need to use bluebird since native promises fulfill all the requirements.

**Comment by bhoriuchi** [comment]
The code base for this project has been modernized and additional methods have been added. version `1.0.0` has been published to npm. See updated readme for api and release section for breaking changes.

**Comment by neuhaus** [comment]
Great, thanks

**Comment by bhoriuchi** [comment]
@neuhaus  i accidentally published with some dependencies that should have been added as devDependencies. I have corrected this and published v1.0.2 to npm.
