### ISSUE TITLE
add dependencies

### ISSUE THREAD

**Issue by neuhaus** [bhoriuchi/readline-promise#2]
package.json contains no dependencies, however this module depends on the readline module.

you may also want to add
```
  "engines": {
    "node": ">=4.8.7"
},
```
to package.json because this module requires a version of node with support for Promises.

**Comment by bhoriuchi** [comment]
is it necessary to add a core library as a dependency?

**Comment by neuhaus** [comment]
If you want to make sure you have a particular version.

**Comment by bhoriuchi** [comment]
i will add them as peerDependencies

**Comment by bhoriuchi** [comment]
Upon looking at this further it seems that you may be referencing https://www.npmjs.com/package/readline which has a different api than the core readline library so I wont be adding it to the dependencies.
