### ISSUE TITLE
Add support for the "question" method

### ISSUE THREAD

**Issue by machineghost** [bhoriuchi/readline-promise#3]
This library is great, except it seems to have left out a key part of the `readline` API out: the `question` method.

Currently if I log the method in `readline-promise` I see:

    function (query, cb) {
      if (typeof cb === 'function') {
        if (this._questionCallback) {
          this.prompt();
        } else {
          this._oldPrompt = this._prompt;
          this.setPrompt(query);
          this._questionCallback = cb;
          this.prompt();
        }
      }
    } 

In other words, I see the normal (`readline` not `readline-promise`) style `question` function which takes a callback.  It would seem more appropriate for the `readline-promise` version to be something like:

    function (query) {
      if (this._questionCallback) {
        return this.prompt();
      } else {
        this._oldPrompt = this._prompt;
        this.setPrompt(query);
        return this.prompt();
      }
    } 

(The above assumes  `prompt` returns a promise; if not some further adjustment might be necessary.)

Is something like this possible/desired?

**Comment by bhoriuchi** [comment]
In general, methods with callbacks are easy to promisify whereas streams take a bit more work. I can add a `questionAsync` method that would just be something like

```js
function questionAsync(query) {
  return new Promise(resolve => {
    rl.question(query, resolve)
  })
}
```

**Comment by machineghost** [comment]
That would be great.

**Comment by bhoriuchi** [comment]
`v1.0.3` has been published with the `questionAsync` method
